# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "863a580061dfc7f69fd670776b3ddcad"
name = "deadline-validation"
application_url = "https://residential-encountered-included-metal.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "stephenie-checkout-extensibility-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://residential-encountered-included-metal.trycloudflare.com/auth/callback",
  "https://residential-encountered-included-metal.trycloudflare.com/auth/shopify/callback",
  "https://residential-encountered-included-metal.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
